<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Symfony\\Component\\Console\\' => array($vendorDir . '/symfony/console'),
    'Nella\\Doctrine' => array($vendorDir . '/nella/doctrine'),
    'Nella\\Console' => array($vendorDir . '/nella/console'),
    'Kdyby\\Replicator\\' => array($vendorDir . '/kdyby/forms-replicator/src'),
    'Doctrine\\ORM' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DBAL\\Migrations' => array($vendorDir . '/doctrine/migrations/lib'),
    'Doctrine\\DBAL' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common' => array($vendorDir . '/doctrine/common/lib'),
);
